version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version abcd ed
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - aws ssm get-parameters --name "Sample" >> sample.txt 
      - cat sample.txt
      - echo $Environment
  build:
    commands:
      - echo Build started on `date`
      - aws ssm get-parameters --name "Sample2" --with-decryption >> sample2.txt 
      - cat sample2.txt
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - aws ssm get-parameters --name "/test/the/path/sample" --with-decryption >> sample3.txt 
      - cat sample3.txt
      